"""
格式转换和序列化模块

提供稀疏数组的格式转换和文件I/O操作。
"""

from typing import Optional, Union
import os
import numpy as np

from ..core.sparse_array import SparseArray
from ..core.config import SparseArrayConfig, SparseFormat
from ..core.exceptions import SparseArrayError, FormatConversionError


class FileOperationError(SparseArrayError):
    """文件操作错误"""

    def __init__(self, message: str, path: Optional[str] = None, operation: Optional[str] = None):
        self.path = path
        self.operation = operation
        super().__init__(message)


def save_sparse(arr: SparseArray, path: str, format: str = 'npz'):
    """
    保存稀疏数组到文件

    Args:
        arr: 稀疏数组
        path: 文件路径
        format: 文件格式
            - 'npz': NumPy压缩格式（推荐）
            - 'mtx': Matrix Market格式
            - 'bin': 二进制格式

    Raises:
        FileOperationError: 文件操作失败时抛出
    """
    try:
        if format == 'npz':
            _save_npz(arr, path)
        elif format == 'mtx':
            _save_mtx(arr, path)
        elif format == 'bin':
            _save_binary(arr, path)
        else:
            raise ValueError(f"Unsupported format: {format}")
    except PermissionError as e:
        raise FileOperationError(
            f"Permission denied when saving to '{path}': {e}",
            path=path, operation='save'
        )
    except OSError as e:
        raise FileOperationError(
            f"OS error when saving to '{path}': {e}",
            path=path, operation='save'
        )
    except Exception as e:
        raise FileOperationError(
            f"Failed to save sparse array to '{path}': {e}",
            path=path, operation='save'
        )


def _save_npz(arr: SparseArray, path: str):
    """保存为NPZ格式"""
    # 确保目录存在
    dir_path = os.path.dirname(path)
    if dir_path:
        os.makedirs(dir_path, exist_ok=True)

    # 转换为CSR格式保存
    if arr._format:
        csr = arr._format.to_csr() if arr.format != 'csr' else arr._format

        np.savez(
            path,
            shape=np.array(arr.shape),
            data=csr.data,  # type: ignore
            indices=csr.indices,  # type: ignore
            indptr=csr.indptr,  # type: ignore
            format=np.array([arr.format]),
            dtype=np.array([str(arr.dtype)])
        )
    else:
        # 空数组处理
        np.savez(
            path,
            shape=np.array(arr.shape),
            data=np.array([], dtype=arr.dtype),
            indices=np.array([], dtype=np.int32),
            indptr=np.array([0], dtype=np.int32),
            format=np.array([arr.format]),
            dtype=np.array([str(arr.dtype)])
        )


def _save_mtx(arr: SparseArray, path: str):
    """保存为Matrix Market格式"""
    # 转换为COO格式
    # 转换为COO格式
    if arr._format:
        coo = arr._format.to_coo() if arr.format != 'coo' else arr._format

        try:
            with open(path, 'w') as f:
                # 写入头部
                f.write('%%MatrixMarket matrix coordinate real general\n')
                f.write(f'% Generated by sparse_array\n')
                f.write(f'{arr.shape[0]} {arr.shape[1]} {arr.nnz}\n')

                # 写入数据
                if arr.nnz > 0 and hasattr(coo, 'rows') and hasattr(coo, 'cols') and hasattr(coo, 'data'):
                    for i in range(arr.nnz):
                        f.write(f'{coo.rows[i] + 1} {coo.cols[i] + 1} {coo.data[i]}\n')  # type: ignore
        except IOError as e:
            raise FileOperationError(
                f"IO error when writing MTX file '{path}': {e}",
                path=path, operation='save_mtx'
            )


def _save_binary(arr: SparseArray, path: str):
    """保存为二进制格式"""
    # 保存为二进制格式
    if arr._format:
        csr = arr._format.to_csr() if arr.format != 'csr' else arr._format

        try:
            with open(path, 'wb') as f:
                # 写入形状
                np.array([len(arr.shape)], dtype=np.int32).tofile(f)
                np.array(arr.shape, dtype=np.int64).tofile(f)

                # 写入数据类型
                dtype_str = str(arr.dtype)
                np.array([len(dtype_str)], dtype=np.int32).tofile(f)
                f.write(dtype_str.encode())

                # 写入CSR数据
                if hasattr(csr, 'data') and hasattr(csr, 'indices') and hasattr(csr, 'indptr'):
                    np.array([len(csr.data)], dtype=np.int64).tofile(f)  # type: ignore
                    csr.data.tofile(f)  # type: ignore
                    csr.indices.tofile(f)  # type: ignore
                    csr.indptr.tofile(f)  # type: ignore
                else:
                    # 空数据处理
                    np.array([0], dtype=np.int64).tofile(f)
        except IOError as e:
            raise FileOperationError(
                f"IO error when writing binary file '{path}': {e}",
                path=path, operation='save_binary'
            )


def load_sparse(path: str, format: str = 'auto') -> SparseArray:
    """
    从文件加载稀疏数组

    Args:
        path: 文件路径
        format: 文件格式 ('npz', 'mtx', 'bin', 'auto')

    Returns:
        SparseArray: 加载的稀疏数组

    Raises:
        FileOperationError: 文件操作失败时抛出
        FileNotFoundError: 文件不存在时抛出
    """
    # 检查文件是否存在
    if not os.path.exists(path):
        raise FileNotFoundError(f"File not found: '{path}'")

    try:
        if format == 'auto':
            # 根据文件扩展名判断
            ext = os.path.splitext(path)[1].lower()
            if ext == '.npz':
                format = 'npz'
            elif ext == '.mtx':
                format = 'mtx'
            elif ext == '.bin':
                format = 'bin'
            else:
                raise ValueError(f"Cannot determine format from extension: {ext}")

        if format == 'npz':
            return _load_npz(path)
        elif format == 'mtx':
            return _load_mtx(path)
        elif format == 'bin':
            return _load_binary(path)
        else:
            raise ValueError(f"Unsupported format: {format}")
    except FileOperationError:
        raise
    except PermissionError as e:
        raise FileOperationError(
            f"Permission denied when loading from '{path}': {e}",
            path=path, operation='load'
        )
    except Exception as e:
        raise FileOperationError(
            f"Failed to load sparse array from '{path}': {e}",
            path=path, operation='load'
        )


def _load_npz(path: str) -> SparseArray:
    """从NPZ格式加载"""
    try:
        data = np.load(path)

        shape = tuple(data['shape'])
        values = data['data']
        indices = data['indices']
        indptr = data['indptr']

        result = SparseArray.from_csr(shape, values, indices, indptr)
        return result
    except Exception as e:
        raise FileOperationError(
            f"Failed to parse NPZ file '{path}': {e}",
            path=path, operation='load_npz'
        )


def _load_mtx(path: str) -> SparseArray:
    """从Matrix Market格式加载"""
    rows = []
    cols = []
    data = []
    shape = None

    try:
        with open(path, 'r') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('%'):
                    continue

                parts = line.split()
                if shape is None:
                    # 第一行非注释是形状
                    shape = (int(parts[0]), int(parts[1]))
                else:
                    rows.append(int(parts[0]) - 1)  # MTX使用1-based索引
                    cols.append(int(parts[1]) - 1)
                    data.append(float(parts[2]))
    except IOError as e:
        raise FileOperationError(
            f"IO error when reading MTX file '{path}': {e}",
            path=path, operation='load_mtx'
        )
    except (ValueError, IndexError) as e:
        raise FileOperationError(
            f"Invalid MTX format in file '{path}': {e}",
            path=path, operation='load_mtx'
        )

    return SparseArray.from_coo(
        shape,  # type: ignore
        np.array(rows, dtype=np.int32),
        np.array(cols, dtype=np.int32),
        np.array(data, dtype=np.float64)
    )  # type: ignore


def _load_binary(path: str) -> SparseArray:
    """从二进制格式加载"""
    try:
        with open(path, 'rb') as f:
            # 读取形状
            ndim = np.fromfile(f, dtype=np.int32, count=1)[0]
            shape = tuple(np.fromfile(f, dtype=np.int64, count=ndim))

            # 读取数据类型
            dtype_len = np.fromfile(f, dtype=np.int32, count=1)[0]
            dtype_str = f.read(dtype_len).decode()
            dtype = np.dtype(dtype_str)

            # 读取CSR数据
            nnz = np.fromfile(f, dtype=np.int64, count=1)[0]
            data = np.fromfile(f, dtype=dtype, count=nnz)
            indices = np.fromfile(f, dtype=np.int32, count=nnz)
            indptr = np.fromfile(f, dtype=np.int32, count=shape[0] + 1)
    except IOError as e:
        raise FileOperationError(
            f"IO error when reading binary file '{path}': {e}",
            path=path, operation='load_binary'
        )
    except (ValueError, IndexError) as e:
        raise FileOperationError(
            f"Invalid binary format in file '{path}': {e}",
            path=path, operation='load_binary'
        )

    return SparseArray.from_csr(shape, data, indices, indptr)


def convert_format(arr: SparseArray,
                   target_format: Union[str, SparseFormat],
                   config: Optional[SparseArrayConfig] = None) -> SparseArray:
    """
    转换稀疏数组格式

    Args:
        arr: 输入稀疏数组
        target_format: 目标格式
        config: 配置对象

    Returns:
        SparseArray: 转换后的稀疏数组
    """
    config = config or SparseArrayConfig()

    if isinstance(target_format, str):
        target_format = SparseFormat(target_format.lower())

    return arr.to_format(target_format)
